### ISSUE TITLE
Error when trying to make .cli_support

### ISSUE THREAD

**Issue by DavidOcacho** [croconut/godot-tester#35]
Hey! I'm facing this error when trying to use the action. 

```
Downloading Godot from:  https://downloads.tuxfamily.org/godotengine/4.1/Godot_v4.1-stable_linux.x86_64.zip
(node:1) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Unzipping Godot...
Godot unzipped to:  /tmp/Godot_v4.1-stable_linux.x86_64
exePath:  /tmp/Godot_v4.1-stable_linux.x86_64
node:fs:1382
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, mkdir '/github/workspace/addons/gut/.cli_support'
    at Object.mkdirSync (node:fs:1382:3)
    at addRebuilderSceneToProjectAddonFolder (/usr/lib/RunGodotImport/helpers/ImportRebuilderHelpers/ImportRebuilderHelpers.js:[24](https://github.com/Ocacho-Games/Home-Godot/actions/runs/5671711739/job/15369416244#step:7:25):12)
    at runGodotImport (/usr/lib/RunGodotImport/RunGodotImport.js:13:5)
    at runTests (/index.js:13:5) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/github/workspace/addons/gut/.cli_support'
}
```

This is the setup I have for the action

```
    - name: Passing GUT Tests
      uses: croconut/godot-tester@v5
      with:
        # required
        version: "4.1"
```

**Comment by croconut** [comment]
Looks like you may need to specify your project directory (path: 'godot'), let me know if that fixes it for you.

**Comment by DavidOcacho** [comment]
That outputs the same error, that was the first thing that I tried

**Comment by croconut** [comment]
Can you give the full logs from when you specified the path? As well as the file path to the Godot directory and gut folders. You could also try with the previous version on 4.1, we may have had a regression since we just had a pretty big rewrite

**Comment by DavidOcacho** [comment]
This is the full log:

```
/usr/bin/docker run --name c9a4a580b42e4eef7d4c48be86c35edc8d6065_533c34 --label c9a4a5 --workdir /github/workspace --rm -e "GITHUB_TOKEN" -e "DISCORD_WEBHOOK" -e "INPUT_VERSION" -e "INPUT_RELEASE_TYPE" -e "INPUT_IS-MONO" -e "INPUT_PATH" -e "INPUT_IMPORT-TIME" -e "INPUT_TEST-TIMEOUT" -e "INPUT_MINIMUM-PASS" -e "INPUT_TEST-DIR" -e "INPUT_CONFIG-FILE" -e "INPUT_RESULT-OUTPUT-FILE" -e "INPUT_DIRECT-SCENE" -e "INPUT_ASSERT-CHECK" -e "INPUT_MAX-FAILS" -e "INPUT_CUSTOM-GODOT-DL-URL" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Home-Godot/Home-Godot":"/github/workspace" c9a4a5:80b42e4eef7d4c48be86c35edc8d6065  "--godot-version" "4.0.3" "--release-type" "rc2" "--path" "godot" "--is-mono" "true" "--import-time" "5" "--test-timeout" "45" "--minimum-pass" "1.0" "--test-dir" "res://test" "--direct-scene" "false" "--assert-check" "false" "--max-fails" "false" "--config-file" "res://.gut_editor_config.json" "--custom-godot-dl-url" "" "--result-output-file" "test_results.xml"
Downloading Godot from:  https://downloads.tuxfamily.org/godotengine/4.0.3/rc2/mono/Godot_v4.0.3-rc2_mono_linux_x86_64.zip
(node:1) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Unzipping Godot...
Godot unzipped to:  /tmp/Godot_v4.0.3-rc2_mono_linux_x86_64/Godot_v4.0.3-rc2_mono_linux.x86_64
exePath:  /tmp/Godot_v4.0.3-rc2_mono_linux_x86_64/Godot_v4.0.3-rc2_mono_linux.x86_64
node:fs:1382
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, mkdir '/github/workspace/godot/addons/gut/.cli_support'
    at Object.mkdirSync (node:fs:1382:3)
    at addRebuilderSceneToProjectAddonFolder (/usr/lib/RunGodotImport/helpers/ImportRebuilderHelpers/ImportRebuilderHelpers.js:[24](https://github.com/Ocacho-Games/Home-Godot/actions/runs/5691111076/job/15425682089#step:4:25):12)
    at runGodotImport (/usr/lib/RunGodotImport/RunGodotImport.js:13:5)
    at runTests (/index.js:13:5) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/github/workspace/godot/addons/gut/.cli_support'
}
```

This is my configuration:

```
jobs:
  pass_tests:
    name: Passing GUT Tests
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: croconut/godot-tester@v5
        with:
          version: "4.0.3"
          release_type: "rc2"
          is-mono: "true"
          path: "godot"
          import-time: "5"
          test-timeout: "45"
          minimum-pass: "1.0"
          test-dir: "res://test"
          config-file: "res://.gut_editor_config.json" 
          result-output-file: "test_results.xml"
```

This is a photo of my repository:
![image](https://github.com/croconut/godot-tester/assets/126606809/07110a31-ecfe-414a-85d0-0b61a2ad8846)

And this is a photo of the godot folder:

![image](https://github.com/croconut/godot-tester/assets/126606809/4870e0fc-b858-4087-b67c-3289e52a3c92)
